/* 
 * File:   mcal_interrupt_gen_config.h
 * Author: AhmedSamy
 *
 * Created on September 28, 2023, 3:00 AM
 */

#ifndef MCAL_INTERRUPT_GEN_CONFIG_H
#define	MCAL_INTERRUPT_GEN_CONFIG_H


#define INTERRUPT_FEATURE_ENABLE        1U

#define INTERRUPT_PRIORITY_LEVELS_ENABLE             INTERRUPT_FEATURE_ENABLE

#define EXT_INTERRUPT_FEATURE_ENABLE                 INTERRUPT_FEATURE_ENABLE

#define EXT_INTERRUPT_INTx_FEATURE_ENABLE            INTERRUPT_FEATURE_ENABLE

#define EXT_INTERRUPT_OnChange_FEATURE_ENABLE        INTERRUPT_FEATURE_ENABLE


#endif	/* MCAL_INTERRUPT_GEN_CONFIG_H */

